#!/bin/bash
# we'll go with bash as that will give us array support

declare -a verbs=()
declare -a verbfuncs=()

register() {
	if [ "$#" != 2 ]; then
		echo "Usage: register verb verbfunction"
	fi
	verb="$1"
	verbfunc="$2"
	verbs[${#verbs[*]}]="$verb"
	verbfuncs[${#verbfuncs[*]}]="$verbfunc"
}

check() {
	printf "%-72s" "${1:0:72}"
}

pass() {
	printf "[ \e[32mPASS\e[0m ]\n"
}

fail() {
	printf "[ \e[31mFAIL\e[0m ]\n"
}

# vim: filetype=sh
