#!/bin/bash
# we'll go with bash as that will give us array support

declare -a verbs=()
declare -a verbfuncs=()
declare -a verbauto=()

register() {
	if [ "$#" != 2 -a "$#" != 3 ]; then
		echo "Usage: register verb verbfunction [flags]"
		return
	fi
	verb="$1"
	verbfunc="$2"
	nextverb=${#verbs[*]}
	shift
	verbs[$nextverb]="$verb"
	verbfuncs[$nextverb]="$verbfunc"
	verbauto[$nextverb]="true"
	while shift; do
		if [ "$1" = "noauto" ]; then
			verbauto[$nextverb]="false"
		fi
	done
}

check() {
	printf "%-72s" "${1:0:72}"
}

pass() {
	printf "[ \e[32mPASS\e[0m ]\n"
}

fail() {
	printf "[ \e[31mFAIL\e[0m ]\n"
}

# vim: filetype=sh
